ncaa_longhorns:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth-secrets
      token: "{{ env_var('GCP_ACCESS_TOKEN') }}"
      refresh_token: "unused"
      client_id: "unused"
      client_secret: "unused"
      token_uri: https://oauth2.googleapis.com/token
      project: da-hackathon-2026
      dataset: texas_longhorns
      location: US
      threads: 4
      job_retries: 1
      job_execution_timeout_seconds: 300
      maximum_bytes_billed: 20000000000
